### ISSUE TITLE
getting-started.ipynb tutorial has misnamed function compute_gene_stats; should use model_overdispersed_genes

### ISSUE THREAD

**Issue by whtns** [MorrissyLab/mosaicMPI#22]
Hi, I appreciate these tutorials. I think there is a misnamed function at least in the notebook. tutorial has misnamed function compute_gene_stats; should use model_overdispersed_genes

**Comment by verheytb** [comment]
Hi, you are correct, thanks for pointing that out. Looks like the error is only in the tutorial. Will be fixed in v2.5.1.
